
package start;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Przyjazd", targetNamespace = "http://start/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Przyjazd {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(name = "number", targetNamespace = "")
    @RequestWrapper(localName = "getNumber", targetNamespace = "http://start/", className = "start.GetNumber")
    @ResponseWrapper(localName = "getNumberResponse", targetNamespace = "http://start/", className = "start.GetNumberResponse")
    public List<Integer> getNumber();

    /**
     * 
     * @param type
     * @return
     *     returns java.util.List<start.Place>
     */
    @WebMethod
    @WebResult(name = "list", targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://start/", className = "start.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://start/", className = "start.GetListResponse")
    public List<Place> getList(
        @WebParam(name = "type", targetNamespace = "")
        int type);

}
